### ISSUE TITLE
Flux spectrum for pi0 in the compressed data file

### ISSUE THREAD

**Issue by hongwanliu** [Harvard-Neutrino/HeavenlyMCP#1]
Hi, 

Thanks for providing this data, I'm finding it really useful. You provided a compressed data file with all the flux spectra from various hadrons, but I think the pi0 file got accidentally overwritten, and doesn't provide the full scan over parameter space, unlike the files for the other hadrons. Would you mind providing the complete file? That would be very helpful and save users some time. Thanks.

Hongwan Liu

**Comment by TheVictorMunoz** [comment]
Hi Hongwan Liu, 

Thanks for calling our attention with this issue. The pi0 file was overwritten when testing the scripts, we have updated the file with the full parameter space and now is ready to use.

Cheers,
Víctor
